# Generated by Django 5.2 on 2025-04-20 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('payment_day', models.PositiveSmallIntegerField(verbose_name='Dia do Pagamento')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago')], default='pending', max_length=10, verbose_name='Status do Pagamento')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Último Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['name'],
            },
        ),
    ]
