# Generated by Django 5.2 on 2025-05-29 16:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Obra')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('is_active', models.BooleanField(default=True, verbose_name='Obra Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_meal_allowance_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Último Pagamento de Vale Refeição'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_salary_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Último Pagamento de Salário'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_transport_allowance_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Último Pagamento de Vale Transporte'),
        ),
        migrations.AddField(
            model_name='employee',
            name='meal_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Vale Refeição'),
        ),
        migrations.AddField(
            model_name='employee',
            name='meal_allowance_amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Valor do Vale Refeição Pago'),
        ),
        migrations.AddField(
            model_name='employee',
            name='meal_allowance_payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('partial', 'Parcial')], default='pending', max_length=10, verbose_name='Status do Pagamento do Vale Refeição'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor do Salário Pago'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('partial', 'Parcial')], default='pending', max_length=10, verbose_name='Status do Pagamento do Salário'),
        ),
        migrations.AddField(
            model_name='employee',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Vale Transporte'),
        ),
        migrations.AddField(
            model_name='employee',
            name='transport_allowance_amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Valor do Vale Transporte Pago'),
        ),
        migrations.AddField(
            model_name='employee',
            name='transport_allowance_payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('partial', 'Parcial')], default='pending', max_length=10, verbose_name='Status do Pagamento do Vale Transporte'),
        ),
        migrations.AddField(
            model_name='employee',
            name='construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.construction', verbose_name='Obra'),
        ),
        migrations.CreateModel(
            name='ConstructionSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Setor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='employees.construction', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Setor da Obra',
                'verbose_name_plural': 'Setores das Obras',
                'ordering': ['construction', 'name'],
                'unique_together': {('name', 'construction')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='construction_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.constructionsector', verbose_name='Setor da Obra'),
        ),
    ]
